version: 1
config:
  - type: nameserver
    address:
      - 1.1.1.1
      - 8.8.8.8
  - type: physical
    name: ens2
    subnets:
     - control: auto
       type: static
       address: {{.Address}}/24
       gateway: 192.168.245.1
